services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=counter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=counter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

volumes:
  pgdata:
